/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as MasterRouteImport } from './routes/_master'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterMasterRouteImport } from './routes/_master.master'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDashboardIndexRouteImport } from './routes/_app.dashboard.index'
import { Route as MasterMasterUsersRouteImport } from './routes/_master.master.users'
import { Route as MasterMasterPlansRouteImport } from './routes/_master.master.plans'
import { Route as MasterMasterOrganizationsRouteImport } from './routes/_master.master.organizations'
import { Route as MasterMasterLogsRouteImport } from './routes/_master.master.logs'
import { Route as AppDashboardSettingsRouteImport } from './routes/_app.dashboard.settings'
import { Route as AppDashboardSalesRouteImport } from './routes/_app.dashboard.sales'
import { Route as AppDashboardLeadsRouteImport } from './routes/_app.dashboard.leads'
import { Route as AppDashboardIntegrationsRouteImport } from './routes/_app.dashboard.integrations'
import { Route as AppDashboardInboxRouteImport } from './routes/_app.dashboard.inbox'
import { Route as AppDashboardCampaignsRouteImport } from './routes/_app.dashboard.campaigns'
import { Route as AppDashboardBuilderRouteImport } from './routes/_app.dashboard.builder'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/_master',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterMasterRoute = MasterMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => MasterRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const MasterMasterUsersRoute = MasterMasterUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MasterMasterRoute,
} as any)
const MasterMasterPlansRoute = MasterMasterPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => MasterMasterRoute,
} as any)
const MasterMasterOrganizationsRoute =
  MasterMasterOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => MasterMasterRoute,
  } as any)
const MasterMasterLogsRoute = MasterMasterLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => MasterMasterRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSalesRoute = AppDashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardLeadsRoute = AppDashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardIntegrationsRoute =
  AppDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppDashboardRoute,
  } as any)
const AppDashboardInboxRoute = AppDashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardCampaignsRoute = AppDashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardBuilderRoute = AppDashboardBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/master': typeof MasterMasterRouteWithChildren
  '/dashboard/builder': typeof AppDashboardBuilderRoute
  '/dashboard/campaigns': typeof AppDashboardCampaignsRoute
  '/dashboard/inbox': typeof AppDashboardInboxRoute
  '/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/dashboard/leads': typeof AppDashboardLeadsRoute
  '/dashboard/sales': typeof AppDashboardSalesRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/master/logs': typeof MasterMasterLogsRoute
  '/master/organizations': typeof MasterMasterOrganizationsRoute
  '/master/plans': typeof MasterMasterPlansRoute
  '/master/users': typeof MasterMasterUsersRoute
  '/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/master': typeof MasterMasterRouteWithChildren
  '/dashboard/builder': typeof AppDashboardBuilderRoute
  '/dashboard/campaigns': typeof AppDashboardCampaignsRoute
  '/dashboard/inbox': typeof AppDashboardInboxRoute
  '/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/dashboard/leads': typeof AppDashboardLeadsRoute
  '/dashboard/sales': typeof AppDashboardSalesRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/master/logs': typeof MasterMasterLogsRoute
  '/master/organizations': typeof MasterMasterOrganizationsRoute
  '/master/plans': typeof MasterMasterPlansRoute
  '/master/users': typeof MasterMasterUsersRoute
  '/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_master': typeof MasterRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_master/master': typeof MasterMasterRouteWithChildren
  '/_app/dashboard/builder': typeof AppDashboardBuilderRoute
  '/_app/dashboard/campaigns': typeof AppDashboardCampaignsRoute
  '/_app/dashboard/inbox': typeof AppDashboardInboxRoute
  '/_app/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/_app/dashboard/leads': typeof AppDashboardLeadsRoute
  '/_app/dashboard/sales': typeof AppDashboardSalesRoute
  '/_app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/_master/master/logs': typeof MasterMasterLogsRoute
  '/_master/master/organizations': typeof MasterMasterOrganizationsRoute
  '/_master/master/plans': typeof MasterMasterPlansRoute
  '/_master/master/users': typeof MasterMasterUsersRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/master'
    | '/dashboard/builder'
    | '/dashboard/campaigns'
    | '/dashboard/inbox'
    | '/dashboard/integrations'
    | '/dashboard/leads'
    | '/dashboard/sales'
    | '/dashboard/settings'
    | '/master/logs'
    | '/master/organizations'
    | '/master/plans'
    | '/master/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/master'
    | '/dashboard/builder'
    | '/dashboard/campaigns'
    | '/dashboard/inbox'
    | '/dashboard/integrations'
    | '/dashboard/leads'
    | '/dashboard/sales'
    | '/dashboard/settings'
    | '/master/logs'
    | '/master/organizations'
    | '/master/plans'
    | '/master/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_master'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_app/dashboard'
    | '/_master/master'
    | '/_app/dashboard/builder'
    | '/_app/dashboard/campaigns'
    | '/_app/dashboard/inbox'
    | '/_app/dashboard/integrations'
    | '/_app/dashboard/leads'
    | '/_app/dashboard/sales'
    | '/_app/dashboard/settings'
    | '/_master/master/logs'
    | '/_master/master/organizations'
    | '/_master/master/plans'
    | '/_master/master/users'
    | '/_app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MasterRoute: typeof MasterRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_master': {
      id: '/_master'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_master/master': {
      id: '/_master/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterMasterRouteImport
      parentRoute: typeof MasterRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_master/master/users': {
      id: '/_master/master/users'
      path: '/users'
      fullPath: '/master/users'
      preLoaderRoute: typeof MasterMasterUsersRouteImport
      parentRoute: typeof MasterMasterRoute
    }
    '/_master/master/plans': {
      id: '/_master/master/plans'
      path: '/plans'
      fullPath: '/master/plans'
      preLoaderRoute: typeof MasterMasterPlansRouteImport
      parentRoute: typeof MasterMasterRoute
    }
    '/_master/master/organizations': {
      id: '/_master/master/organizations'
      path: '/organizations'
      fullPath: '/master/organizations'
      preLoaderRoute: typeof MasterMasterOrganizationsRouteImport
      parentRoute: typeof MasterMasterRoute
    }
    '/_master/master/logs': {
      id: '/_master/master/logs'
      path: '/logs'
      fullPath: '/master/logs'
      preLoaderRoute: typeof MasterMasterLogsRouteImport
      parentRoute: typeof MasterMasterRoute
    }
    '/_app/dashboard/settings': {
      id: '/_app/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/sales': {
      id: '/_app/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof AppDashboardSalesRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/leads': {
      id: '/_app/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof AppDashboardLeadsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/integrations': {
      id: '/_app/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AppDashboardIntegrationsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/inbox': {
      id: '/_app/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof AppDashboardInboxRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/campaigns': {
      id: '/_app/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof AppDashboardCampaignsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/builder': {
      id: '/_app/dashboard/builder'
      path: '/builder'
      fullPath: '/dashboard/builder'
      preLoaderRoute: typeof AppDashboardBuilderRouteImport
      parentRoute: typeof AppDashboardRoute
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardBuilderRoute: typeof AppDashboardBuilderRoute
  AppDashboardCampaignsRoute: typeof AppDashboardCampaignsRoute
  AppDashboardInboxRoute: typeof AppDashboardInboxRoute
  AppDashboardIntegrationsRoute: typeof AppDashboardIntegrationsRoute
  AppDashboardLeadsRoute: typeof AppDashboardLeadsRoute
  AppDashboardSalesRoute: typeof AppDashboardSalesRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardBuilderRoute: AppDashboardBuilderRoute,
  AppDashboardCampaignsRoute: AppDashboardCampaignsRoute,
  AppDashboardInboxRoute: AppDashboardInboxRoute,
  AppDashboardIntegrationsRoute: AppDashboardIntegrationsRoute,
  AppDashboardLeadsRoute: AppDashboardLeadsRoute,
  AppDashboardSalesRoute: AppDashboardSalesRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MasterMasterRouteChildren {
  MasterMasterLogsRoute: typeof MasterMasterLogsRoute
  MasterMasterOrganizationsRoute: typeof MasterMasterOrganizationsRoute
  MasterMasterPlansRoute: typeof MasterMasterPlansRoute
  MasterMasterUsersRoute: typeof MasterMasterUsersRoute
}

const MasterMasterRouteChildren: MasterMasterRouteChildren = {
  MasterMasterLogsRoute: MasterMasterLogsRoute,
  MasterMasterOrganizationsRoute: MasterMasterOrganizationsRoute,
  MasterMasterPlansRoute: MasterMasterPlansRoute,
  MasterMasterUsersRoute: MasterMasterUsersRoute,
}

const MasterMasterRouteWithChildren = MasterMasterRoute._addFileChildren(
  MasterMasterRouteChildren,
)

interface MasterRouteChildren {
  MasterMasterRoute: typeof MasterMasterRouteWithChildren
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterMasterRoute: MasterMasterRouteWithChildren,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MasterRoute: MasterRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
