/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as MasterRouteImport } from './routes/_master'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as MasterMasterIndexRouteImport } from './routes/_master.master.index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app.dashboard.index'
import { Route as MasterMasterUsersRouteImport } from './routes/_master.master.users'
import { Route as MasterMasterPlatformRouteImport } from './routes/_master.master.platform'
import { Route as MasterMasterPlansRouteImport } from './routes/_master.master.plans'
import { Route as MasterMasterOrganizationsRouteImport } from './routes/_master.master.organizations'
import { Route as MasterMasterLogsRouteImport } from './routes/_master.master.logs'
import { Route as MasterMasterAiRouteImport } from './routes/_master.master.ai'
import { Route as MasterMasterAgentQueueRouteImport } from './routes/_master.master.agent-queue'
import { Route as AppDashboardSettingsRouteImport } from './routes/_app.dashboard.settings'
import { Route as AppDashboardPipelineRouteImport } from './routes/_app.dashboard.pipeline'
import { Route as AppDashboardLeadsRouteImport } from './routes/_app.dashboard.leads'
import { Route as AppDashboardIntegrationsRouteImport } from './routes/_app.dashboard.integrations'
import { Route as AppDashboardInboxRouteImport } from './routes/_app.dashboard.inbox'
import { Route as AppDashboardCampaignsRouteImport } from './routes/_app.dashboard.campaigns'
import { Route as AppDashboardLeadsIndexRouteImport } from './routes/_app.dashboard.leads.index'
import { Route as AppDashboardBuilderIndexRouteImport } from './routes/_app.dashboard.builder.index'
import { Route as ApiPublicHooksRunFlowTickRouteImport } from './routes/api/public/hooks/run-flow-tick'
import { Route as ApiPublicHooksCalcomRouteImport } from './routes/api/public/hooks/calcom'
import { Route as ApiPublicHooksAgentTickRouteImport } from './routes/api/public/hooks/agent-tick'
import { Route as MasterMasterLeadsLeadIdRouteImport } from './routes/_master.master.leads.$leadId'
import { Route as AppDashboardLeadsApolloRouteImport } from './routes/_app.dashboard.leads.apollo'
import { Route as AppDashboardLeadsLeadIdRouteImport } from './routes/_app.dashboard.leads.$leadId'
import { Route as AppDashboardBuilderDocumentIdRouteImport } from './routes/_app.dashboard.builder.$documentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/_master',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const MasterMasterIndexRoute = MasterMasterIndexRouteImport.update({
  id: '/master/',
  path: '/master/',
  getParentRoute: () => MasterRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const MasterMasterUsersRoute = MasterMasterUsersRouteImport.update({
  id: '/master/users',
  path: '/master/users',
  getParentRoute: () => MasterRoute,
} as any)
const MasterMasterPlatformRoute = MasterMasterPlatformRouteImport.update({
  id: '/master/platform',
  path: '/master/platform',
  getParentRoute: () => MasterRoute,
} as any)
const MasterMasterPlansRoute = MasterMasterPlansRouteImport.update({
  id: '/master/plans',
  path: '/master/plans',
  getParentRoute: () => MasterRoute,
} as any)
const MasterMasterOrganizationsRoute =
  MasterMasterOrganizationsRouteImport.update({
    id: '/master/organizations',
    path: '/master/organizations',
    getParentRoute: () => MasterRoute,
  } as any)
const MasterMasterLogsRoute = MasterMasterLogsRouteImport.update({
  id: '/master/logs',
  path: '/master/logs',
  getParentRoute: () => MasterRoute,
} as any)
const MasterMasterAiRoute = MasterMasterAiRouteImport.update({
  id: '/master/ai',
  path: '/master/ai',
  getParentRoute: () => MasterRoute,
} as any)
const MasterMasterAgentQueueRoute = MasterMasterAgentQueueRouteImport.update({
  id: '/master/agent-queue',
  path: '/master/agent-queue',
  getParentRoute: () => MasterRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardPipelineRoute = AppDashboardPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardLeadsRoute = AppDashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardIntegrationsRoute =
  AppDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppDashboardRoute,
  } as any)
const AppDashboardInboxRoute = AppDashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardCampaignsRoute = AppDashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardLeadsIndexRoute = AppDashboardLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardLeadsRoute,
} as any)
const AppDashboardBuilderIndexRoute =
  AppDashboardBuilderIndexRouteImport.update({
    id: '/builder/',
    path: '/builder/',
    getParentRoute: () => AppDashboardRoute,
  } as any)
const ApiPublicHooksRunFlowTickRoute =
  ApiPublicHooksRunFlowTickRouteImport.update({
    id: '/api/public/hooks/run-flow-tick',
    path: '/api/public/hooks/run-flow-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCalcomRoute = ApiPublicHooksCalcomRouteImport.update({
  id: '/api/public/hooks/calcom',
  path: '/api/public/hooks/calcom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAgentTickRoute = ApiPublicHooksAgentTickRouteImport.update({
  id: '/api/public/hooks/agent-tick',
  path: '/api/public/hooks/agent-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterMasterLeadsLeadIdRoute = MasterMasterLeadsLeadIdRouteImport.update({
  id: '/master/leads/$leadId',
  path: '/master/leads/$leadId',
  getParentRoute: () => MasterRoute,
} as any)
const AppDashboardLeadsApolloRoute = AppDashboardLeadsApolloRouteImport.update({
  id: '/apollo',
  path: '/apollo',
  getParentRoute: () => AppDashboardLeadsRoute,
} as any)
const AppDashboardLeadsLeadIdRoute = AppDashboardLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppDashboardLeadsRoute,
} as any)
const AppDashboardBuilderDocumentIdRoute =
  AppDashboardBuilderDocumentIdRouteImport.update({
    id: '/builder/$documentId',
    path: '/builder/$documentId',
    getParentRoute: () => AppDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/campaigns': typeof AppDashboardCampaignsRoute
  '/dashboard/inbox': typeof AppDashboardInboxRoute
  '/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/dashboard/leads': typeof AppDashboardLeadsRouteWithChildren
  '/dashboard/pipeline': typeof AppDashboardPipelineRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/master/agent-queue': typeof MasterMasterAgentQueueRoute
  '/master/ai': typeof MasterMasterAiRoute
  '/master/logs': typeof MasterMasterLogsRoute
  '/master/organizations': typeof MasterMasterOrganizationsRoute
  '/master/plans': typeof MasterMasterPlansRoute
  '/master/platform': typeof MasterMasterPlatformRoute
  '/master/users': typeof MasterMasterUsersRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/master/': typeof MasterMasterIndexRoute
  '/dashboard/builder/$documentId': typeof AppDashboardBuilderDocumentIdRoute
  '/dashboard/leads/$leadId': typeof AppDashboardLeadsLeadIdRoute
  '/dashboard/leads/apollo': typeof AppDashboardLeadsApolloRoute
  '/master/leads/$leadId': typeof MasterMasterLeadsLeadIdRoute
  '/api/public/hooks/agent-tick': typeof ApiPublicHooksAgentTickRoute
  '/api/public/hooks/calcom': typeof ApiPublicHooksCalcomRoute
  '/api/public/hooks/run-flow-tick': typeof ApiPublicHooksRunFlowTickRoute
  '/dashboard/builder/': typeof AppDashboardBuilderIndexRoute
  '/dashboard/leads/': typeof AppDashboardLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/campaigns': typeof AppDashboardCampaignsRoute
  '/dashboard/inbox': typeof AppDashboardInboxRoute
  '/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/dashboard/pipeline': typeof AppDashboardPipelineRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/master/agent-queue': typeof MasterMasterAgentQueueRoute
  '/master/ai': typeof MasterMasterAiRoute
  '/master/logs': typeof MasterMasterLogsRoute
  '/master/organizations': typeof MasterMasterOrganizationsRoute
  '/master/plans': typeof MasterMasterPlansRoute
  '/master/platform': typeof MasterMasterPlatformRoute
  '/master/users': typeof MasterMasterUsersRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/master': typeof MasterMasterIndexRoute
  '/dashboard/builder/$documentId': typeof AppDashboardBuilderDocumentIdRoute
  '/dashboard/leads/$leadId': typeof AppDashboardLeadsLeadIdRoute
  '/dashboard/leads/apollo': typeof AppDashboardLeadsApolloRoute
  '/master/leads/$leadId': typeof MasterMasterLeadsLeadIdRoute
  '/api/public/hooks/agent-tick': typeof ApiPublicHooksAgentTickRoute
  '/api/public/hooks/calcom': typeof ApiPublicHooksCalcomRoute
  '/api/public/hooks/run-flow-tick': typeof ApiPublicHooksRunFlowTickRoute
  '/dashboard/builder': typeof AppDashboardBuilderIndexRoute
  '/dashboard/leads': typeof AppDashboardLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_master': typeof MasterRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_app/dashboard/campaigns': typeof AppDashboardCampaignsRoute
  '/_app/dashboard/inbox': typeof AppDashboardInboxRoute
  '/_app/dashboard/integrations': typeof AppDashboardIntegrationsRoute
  '/_app/dashboard/leads': typeof AppDashboardLeadsRouteWithChildren
  '/_app/dashboard/pipeline': typeof AppDashboardPipelineRoute
  '/_app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/_master/master/agent-queue': typeof MasterMasterAgentQueueRoute
  '/_master/master/ai': typeof MasterMasterAiRoute
  '/_master/master/logs': typeof MasterMasterLogsRoute
  '/_master/master/organizations': typeof MasterMasterOrganizationsRoute
  '/_master/master/plans': typeof MasterMasterPlansRoute
  '/_master/master/platform': typeof MasterMasterPlatformRoute
  '/_master/master/users': typeof MasterMasterUsersRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_master/master/': typeof MasterMasterIndexRoute
  '/_app/dashboard/builder/$documentId': typeof AppDashboardBuilderDocumentIdRoute
  '/_app/dashboard/leads/$leadId': typeof AppDashboardLeadsLeadIdRoute
  '/_app/dashboard/leads/apollo': typeof AppDashboardLeadsApolloRoute
  '/_master/master/leads/$leadId': typeof MasterMasterLeadsLeadIdRoute
  '/api/public/hooks/agent-tick': typeof ApiPublicHooksAgentTickRoute
  '/api/public/hooks/calcom': typeof ApiPublicHooksCalcomRoute
  '/api/public/hooks/run-flow-tick': typeof ApiPublicHooksRunFlowTickRoute
  '/_app/dashboard/builder/': typeof AppDashboardBuilderIndexRoute
  '/_app/dashboard/leads/': typeof AppDashboardLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/invite/$token'
    | '/dashboard/campaigns'
    | '/dashboard/inbox'
    | '/dashboard/integrations'
    | '/dashboard/leads'
    | '/dashboard/pipeline'
    | '/dashboard/settings'
    | '/master/agent-queue'
    | '/master/ai'
    | '/master/logs'
    | '/master/organizations'
    | '/master/plans'
    | '/master/platform'
    | '/master/users'
    | '/dashboard/'
    | '/master/'
    | '/dashboard/builder/$documentId'
    | '/dashboard/leads/$leadId'
    | '/dashboard/leads/apollo'
    | '/master/leads/$leadId'
    | '/api/public/hooks/agent-tick'
    | '/api/public/hooks/calcom'
    | '/api/public/hooks/run-flow-tick'
    | '/dashboard/builder/'
    | '/dashboard/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/invite/$token'
    | '/dashboard/campaigns'
    | '/dashboard/inbox'
    | '/dashboard/integrations'
    | '/dashboard/pipeline'
    | '/dashboard/settings'
    | '/master/agent-queue'
    | '/master/ai'
    | '/master/logs'
    | '/master/organizations'
    | '/master/plans'
    | '/master/platform'
    | '/master/users'
    | '/dashboard'
    | '/master'
    | '/dashboard/builder/$documentId'
    | '/dashboard/leads/$leadId'
    | '/dashboard/leads/apollo'
    | '/master/leads/$leadId'
    | '/api/public/hooks/agent-tick'
    | '/api/public/hooks/calcom'
    | '/api/public/hooks/run-flow-tick'
    | '/dashboard/builder'
    | '/dashboard/leads'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_master'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/dashboard'
    | '/invite/$token'
    | '/_app/dashboard/campaigns'
    | '/_app/dashboard/inbox'
    | '/_app/dashboard/integrations'
    | '/_app/dashboard/leads'
    | '/_app/dashboard/pipeline'
    | '/_app/dashboard/settings'
    | '/_master/master/agent-queue'
    | '/_master/master/ai'
    | '/_master/master/logs'
    | '/_master/master/organizations'
    | '/_master/master/plans'
    | '/_master/master/platform'
    | '/_master/master/users'
    | '/_app/dashboard/'
    | '/_master/master/'
    | '/_app/dashboard/builder/$documentId'
    | '/_app/dashboard/leads/$leadId'
    | '/_app/dashboard/leads/apollo'
    | '/_master/master/leads/$leadId'
    | '/api/public/hooks/agent-tick'
    | '/api/public/hooks/calcom'
    | '/api/public/hooks/run-flow-tick'
    | '/_app/dashboard/builder/'
    | '/_app/dashboard/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MasterRoute: typeof MasterRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicHooksAgentTickRoute: typeof ApiPublicHooksAgentTickRoute
  ApiPublicHooksCalcomRoute: typeof ApiPublicHooksCalcomRoute
  ApiPublicHooksRunFlowTickRoute: typeof ApiPublicHooksRunFlowTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_master': {
      id: '/_master'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_master/master/': {
      id: '/_master/master/'
      path: '/master'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterMasterIndexRouteImport
      parentRoute: typeof MasterRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_master/master/users': {
      id: '/_master/master/users'
      path: '/master/users'
      fullPath: '/master/users'
      preLoaderRoute: typeof MasterMasterUsersRouteImport
      parentRoute: typeof MasterRoute
    }
    '/_master/master/platform': {
      id: '/_master/master/platform'
      path: '/master/platform'
      fullPath: '/master/platform'
      preLoaderRoute: typeof MasterMasterPlatformRouteImport
      parentRoute: typeof MasterRoute
    }
    '/_master/master/plans': {
      id: '/_master/master/plans'
      path: '/master/plans'
      fullPath: '/master/plans'
      preLoaderRoute: typeof MasterMasterPlansRouteImport
      parentRoute: typeof MasterRoute
    }
    '/_master/master/organizations': {
      id: '/_master/master/organizations'
      path: '/master/organizations'
      fullPath: '/master/organizations'
      preLoaderRoute: typeof MasterMasterOrganizationsRouteImport
      parentRoute: typeof MasterRoute
    }
    '/_master/master/logs': {
      id: '/_master/master/logs'
      path: '/master/logs'
      fullPath: '/master/logs'
      preLoaderRoute: typeof MasterMasterLogsRouteImport
      parentRoute: typeof MasterRoute
    }
    '/_master/master/ai': {
      id: '/_master/master/ai'
      path: '/master/ai'
      fullPath: '/master/ai'
      preLoaderRoute: typeof MasterMasterAiRouteImport
      parentRoute: typeof MasterRoute
    }
    '/_master/master/agent-queue': {
      id: '/_master/master/agent-queue'
      path: '/master/agent-queue'
      fullPath: '/master/agent-queue'
      preLoaderRoute: typeof MasterMasterAgentQueueRouteImport
      parentRoute: typeof MasterRoute
    }
    '/_app/dashboard/settings': {
      id: '/_app/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/pipeline': {
      id: '/_app/dashboard/pipeline'
      path: '/pipeline'
      fullPath: '/dashboard/pipeline'
      preLoaderRoute: typeof AppDashboardPipelineRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/leads': {
      id: '/_app/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof AppDashboardLeadsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/integrations': {
      id: '/_app/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AppDashboardIntegrationsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/inbox': {
      id: '/_app/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof AppDashboardInboxRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/campaigns': {
      id: '/_app/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof AppDashboardCampaignsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/leads/': {
      id: '/_app/dashboard/leads/'
      path: '/'
      fullPath: '/dashboard/leads/'
      preLoaderRoute: typeof AppDashboardLeadsIndexRouteImport
      parentRoute: typeof AppDashboardLeadsRoute
    }
    '/_app/dashboard/builder/': {
      id: '/_app/dashboard/builder/'
      path: '/builder'
      fullPath: '/dashboard/builder/'
      preLoaderRoute: typeof AppDashboardBuilderIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/api/public/hooks/run-flow-tick': {
      id: '/api/public/hooks/run-flow-tick'
      path: '/api/public/hooks/run-flow-tick'
      fullPath: '/api/public/hooks/run-flow-tick'
      preLoaderRoute: typeof ApiPublicHooksRunFlowTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/calcom': {
      id: '/api/public/hooks/calcom'
      path: '/api/public/hooks/calcom'
      fullPath: '/api/public/hooks/calcom'
      preLoaderRoute: typeof ApiPublicHooksCalcomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agent-tick': {
      id: '/api/public/hooks/agent-tick'
      path: '/api/public/hooks/agent-tick'
      fullPath: '/api/public/hooks/agent-tick'
      preLoaderRoute: typeof ApiPublicHooksAgentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_master/master/leads/$leadId': {
      id: '/_master/master/leads/$leadId'
      path: '/master/leads/$leadId'
      fullPath: '/master/leads/$leadId'
      preLoaderRoute: typeof MasterMasterLeadsLeadIdRouteImport
      parentRoute: typeof MasterRoute
    }
    '/_app/dashboard/leads/apollo': {
      id: '/_app/dashboard/leads/apollo'
      path: '/apollo'
      fullPath: '/dashboard/leads/apollo'
      preLoaderRoute: typeof AppDashboardLeadsApolloRouteImport
      parentRoute: typeof AppDashboardLeadsRoute
    }
    '/_app/dashboard/leads/$leadId': {
      id: '/_app/dashboard/leads/$leadId'
      path: '/$leadId'
      fullPath: '/dashboard/leads/$leadId'
      preLoaderRoute: typeof AppDashboardLeadsLeadIdRouteImport
      parentRoute: typeof AppDashboardLeadsRoute
    }
    '/_app/dashboard/builder/$documentId': {
      id: '/_app/dashboard/builder/$documentId'
      path: '/builder/$documentId'
      fullPath: '/dashboard/builder/$documentId'
      preLoaderRoute: typeof AppDashboardBuilderDocumentIdRouteImport
      parentRoute: typeof AppDashboardRoute
    }
  }
}

interface AppDashboardLeadsRouteChildren {
  AppDashboardLeadsLeadIdRoute: typeof AppDashboardLeadsLeadIdRoute
  AppDashboardLeadsApolloRoute: typeof AppDashboardLeadsApolloRoute
  AppDashboardLeadsIndexRoute: typeof AppDashboardLeadsIndexRoute
}

const AppDashboardLeadsRouteChildren: AppDashboardLeadsRouteChildren = {
  AppDashboardLeadsLeadIdRoute: AppDashboardLeadsLeadIdRoute,
  AppDashboardLeadsApolloRoute: AppDashboardLeadsApolloRoute,
  AppDashboardLeadsIndexRoute: AppDashboardLeadsIndexRoute,
}

const AppDashboardLeadsRouteWithChildren =
  AppDashboardLeadsRoute._addFileChildren(AppDashboardLeadsRouteChildren)

interface AppDashboardRouteChildren {
  AppDashboardCampaignsRoute: typeof AppDashboardCampaignsRoute
  AppDashboardInboxRoute: typeof AppDashboardInboxRoute
  AppDashboardIntegrationsRoute: typeof AppDashboardIntegrationsRoute
  AppDashboardLeadsRoute: typeof AppDashboardLeadsRouteWithChildren
  AppDashboardPipelineRoute: typeof AppDashboardPipelineRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardBuilderDocumentIdRoute: typeof AppDashboardBuilderDocumentIdRoute
  AppDashboardBuilderIndexRoute: typeof AppDashboardBuilderIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardCampaignsRoute: AppDashboardCampaignsRoute,
  AppDashboardInboxRoute: AppDashboardInboxRoute,
  AppDashboardIntegrationsRoute: AppDashboardIntegrationsRoute,
  AppDashboardLeadsRoute: AppDashboardLeadsRouteWithChildren,
  AppDashboardPipelineRoute: AppDashboardPipelineRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardBuilderDocumentIdRoute: AppDashboardBuilderDocumentIdRoute,
  AppDashboardBuilderIndexRoute: AppDashboardBuilderIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MasterRouteChildren {
  MasterMasterAgentQueueRoute: typeof MasterMasterAgentQueueRoute
  MasterMasterAiRoute: typeof MasterMasterAiRoute
  MasterMasterLogsRoute: typeof MasterMasterLogsRoute
  MasterMasterOrganizationsRoute: typeof MasterMasterOrganizationsRoute
  MasterMasterPlansRoute: typeof MasterMasterPlansRoute
  MasterMasterPlatformRoute: typeof MasterMasterPlatformRoute
  MasterMasterUsersRoute: typeof MasterMasterUsersRoute
  MasterMasterIndexRoute: typeof MasterMasterIndexRoute
  MasterMasterLeadsLeadIdRoute: typeof MasterMasterLeadsLeadIdRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterMasterAgentQueueRoute: MasterMasterAgentQueueRoute,
  MasterMasterAiRoute: MasterMasterAiRoute,
  MasterMasterLogsRoute: MasterMasterLogsRoute,
  MasterMasterOrganizationsRoute: MasterMasterOrganizationsRoute,
  MasterMasterPlansRoute: MasterMasterPlansRoute,
  MasterMasterPlatformRoute: MasterMasterPlatformRoute,
  MasterMasterUsersRoute: MasterMasterUsersRoute,
  MasterMasterIndexRoute: MasterMasterIndexRoute,
  MasterMasterLeadsLeadIdRoute: MasterMasterLeadsLeadIdRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MasterRoute: MasterRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicHooksAgentTickRoute: ApiPublicHooksAgentTickRoute,
  ApiPublicHooksCalcomRoute: ApiPublicHooksCalcomRoute,
  ApiPublicHooksRunFlowTickRoute: ApiPublicHooksRunFlowTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
