DROP POLICY IF EXISTS "Master admins manage all ai_actions" ON public.ai_actions;
DROP POLICY IF EXISTS "Master admins manage all ai_org_profile" ON public.ai_org_profile;
DROP POLICY IF EXISTS "Master admins manage ai_tone_presets" ON public.ai_tone_presets;
DROP POLICY IF EXISTS "Master admins manage all builder_documents" ON public.builder_documents;
DROP POLICY IF EXISTS "Master admins manage all campaign_enrollments" ON public.campaign_enrollments;
DROP POLICY IF EXISTS "Master admins manage all campaigns" ON public.campaigns;
DROP POLICY IF EXISTS "Master admins manage all conversations" ON public.conversations;
DROP POLICY IF EXISTS "Master admins manage all deals" ON public.deals;
DROP POLICY IF EXISTS "Master admins manage all flow_definitions" ON public.flow_definitions;
DROP POLICY IF EXISTS "Master admins manage all flow_edges" ON public.flow_edges;
DROP POLICY IF EXISTS "Master admins manage all flow_nodes" ON public.flow_nodes;
DROP POLICY IF EXISTS "Master admins manage all flow_step_runs" ON public.flow_step_runs;
DROP POLICY IF EXISTS "Master admins manage all flow_steps" ON public.flow_steps;
DROP POLICY IF EXISTS "Master admins manage all flow_transitions" ON public.flow_transitions;
DROP POLICY IF EXISTS "Master admins manage all handoff_events" ON public.handoff_events;
DROP POLICY IF EXISTS "Master admins manage all hook7_instances" ON public.hook7_instances;
DROP POLICY IF EXISTS "Master admins manage all integration credentials" ON public.integration_credentials;
DROP POLICY IF EXISTS "Master admins manage all knowledge chunks" ON public.knowledge_chunks;
DROP POLICY IF EXISTS "Master admins manage all knowledge sources" ON public.knowledge_sources;
DROP POLICY IF EXISTS "Master admins manage all lead activities" ON public.lead_activities;
DROP POLICY IF EXISTS "Master admins manage all lead_bookings" ON public.lead_bookings;
DROP POLICY IF EXISTS "Master admins manage all lead enrichment" ON public.lead_enrichment;
DROP POLICY IF EXISTS "Master admins manage all lead sources" ON public.lead_sources;
DROP POLICY IF EXISTS "Master admins manage all leads" ON public.leads;
DROP POLICY IF EXISTS "Master admins manage all messages" ON public.messages;
DROP POLICY IF EXISTS "Master admins manage all organization_integrations" ON public.organization_integrations;
DROP POLICY IF EXISTS "Master admins manage all outbound_messages" ON public.outbound_messages;
DROP POLICY IF EXISTS "Master admins manage all pipedrive_sync_runs" ON public.pipedrive_sync_runs;
DROP POLICY IF EXISTS "Master admins manage scheduled jobs" ON public.scheduled_jobs;
DROP POLICY IF EXISTS "Master admins manage usage counters" ON public.usage_counters;
DROP POLICY IF EXISTS "Master admins manage webhook_events" ON public.webhook_events;